### ISSUE TITLE
Breakpoint indicator doesn't appear when adding a breakpoint to a file not currently being executed

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#23] opened 2021-06-13 11:18 UTC
~~Let's call the file, containing the current execution point "the currenty loaded file".~~

~~When I click on the line number to toggle a breakpoint, the part of the gutter around the line number should light up (in red, if using the "Dark" preset). This works only if adding a breakpoint in the currently loaded file. If I switch to another file, and add a breakpoint there, then the gutter doesn't show it until the file is loaded. The breakpoint is in fact added (I can see it in the gdb console), it's just the gutter that doesn't indicate that it is.~~

~~Repro:~~
~~1. Compile the attached files with debug symbols via `gcc -g gf-repro.c -o whatever`~~
~~2. Launch it in gf via `gf2 ./whatever`~~
~~3. Press `ctrl+F5` to step into main~~
~~4. Add a breakpoint on line 6 (it works). Remove it~~
~~5. Using the `Files` pane switch to the file `gf-repro-other.c` and then back to `gf-repro.c`~~
~~6. Try to add a breakpoint again on line 6. *This doesn't work*~~

~~Update: switching to another file and then back makes it so that even the currently loaded file doesn't draw breakpoints correctly (until I do a step).~~

I'm not sure what causes the issue, but sometimes the gutter doesn't light up in red as it should.

**Comment by nakst** [comment] 2021-06-13 12:23
I thought I fixed this recently. It was caused by GDB using relative paths to files. See if you can find a reliable way to reproduce it.

**Comment by aolo2** [comment] 2021-06-14 08:14
Ok, I *think* I got it. Below are two files: `main.c` and `other.c`.
1. Compile `main.c` in debug
2. Launch gf **from a different directory than the binary**
3. Press `CTRL+F5` to step into main
4. Use the `Files` pane to switch to `other.c`
5. Try to add a breakpoint anywhere in the file
6. ???
7. Fail (well, the breakpoint is added, but the UI doesn't indicate that it is)

main.c
```
#include "other.c"

int main()
{
	foo();
	return(0);
}
```


other.c
```
void foo()
{
	int a = 1;
	a = a + 1;
}
```

**Comment by nakst** [comment] 2021-06-15 12:52
I don't think there is an easy fix for this. 
GDB appears to use paths relative to the directory in which the symbol file was compiled, which is very unhelpful, especially when there are multiple symbol files/shared libraries. I looked into a few ways to deal with this, and none of them worked. I don't think the added complexity of a fix would be justified if it's only for some edge case of the breakpoint display.
Sadly therefore, my advice is to just run `gf2` from the same directory that you compiled your binary.

**Comment by aolo2** [comment] 2021-06-15 16:07
It appears gdb's `info source` command has the compilation directory. Can't you then 'chdir` to there and load the files using relative paths? Not implying this is the solution, just asking.

**Comment by nakst** [comment] 2021-06-16 12:32
I've added a command in the menu to "Ask GDB for PWD" which does this. 
Note that it only works when the target application has been started.

**Comment by aolo2** [comment] 2021-06-17 14:47
Yeah, that works!

**Closed** 2021-06-17 20:08 UTC
