### ISSUE TITLE
Clipboard doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by makuto** [nakst/gf#66] opened 2022-01-22 22:42 UTC
I have been trying to use Ctrl+C and Ctrl+V in gf, but it neither copies nor pastes. Is this something that needs to be hooked up in the app? I have 43091e7b46da3fb874932d2f56954d109b4d32b4 and built from source.

**Comment by nakst** [comment] 2022-01-22 22:51
Sorry, I tried once, but was ultimately unable to work out how to implement the X11 clipboard API. 

Perhaps someone else will be able to figure it out.

**Comment by khvorov45** [comment] 2022-02-09 02:33
Just started trying to implement clipboard for [luigi](https://github.com/nakst/luigi) textboxes. Will submit a pr there if I figure it out.

**Comment by IWouldRatherUsePasteBin** [comment] 2022-02-10 21:35
Got clipboard support working! All the changes are in luigi.h, and I've put "//@clipboard_change" near all the changes to make it easy to find them.

There is a little catch though, X11 makes it so that when you paste something it creates an event that the program you are pasting from has to respond to by sending over the data. Which means that in order to paste something you copied in gf you have to keep that text in memory. I'm not sure what your general policy for keeping track of that kind of stuff is, so for now I just created a giant global char array, and you can adapt that however you want.

Also when you close gf you lose whatever was in the clipboard (since the program is no longer there to copy from). A lot of linux programs just work this way, and the ones that don't just keep a process running in the background (or try to find a clipboard manager that continuously runs in the background) until the clipboard is replaced. I just went with the "close the program -> lose the text" approach.

I don't work with git much, so I'm going to try to submit a pull request, but in case I fail, here is the pastebin of luigi.h:
[https://pastebin.com/hHuBT3S7](https://pastebin.com/hHuBT3S7)

> Just started trying to implement clipboard for [luigi](https://github.com/nakst/luigi) textboxes. Will submit a pr there if I figure it out.

Oh wow that's a weird coincidence, I must have started implementing clipboard support an hour or two before  you made that comment. Sorry I didn't post about it before doing so, although with the way X11 is, it might be good to have two solutions to compare.

Final note, I don't at all blame nakst for not figuring it out, what should have been a couple minutes tops with a remotely sane API turned into a total nightmare. I swear the X Foundation must have gone up to a mad man having a fever dream and asked "Could you design our API, here's some LSD so you can get creative with it!" And then for documentation, took the post-it notes he scribbled on and an ARG out of it.

Sorry for the rant, don't mean to be negative or be a drag, just had to get that off my chest.

**Comment by khvorov45** [comment] 2022-02-11 09:27
Since I also got my solution working, you can see the pr [here](https://github.com/nakst/luigi/pull/6).

If the string is too large the property you are trying to read from will have an "INCR" atom type and it's value will be the "lower transfer bound" for the incremental transfer X wants you to do. If you try to copy [this string](https://pastebin.com/raw/B7b7mfBN) for example without handling incremental transfers you get this creepy smily face looking at you 
![Screenshot from 2022-02-11 20-19-20](https://user-images.githubusercontent.com/44919476/153566663-fba68838-9090-45e0-aef7-025be8ba8d38.png)
Large string copying not working isn't a big deal here right now, I just thought it was funny.

**Comment by nakst** [comment] 2022-02-11 09:40
Please note that `_UIProcessEvent` is not reentrant, except in special cases for the dialog box. You will need to change this to either queue up input events and process them later, or discard them.

**Comment by khvorov45** [comment] 2022-02-11 12:05
See #69. 
There is still a bug here - inability to copy/paste within a gf window caused by incorrectly expecting the next event to always be `SelectionNotify`.

**Comment by nakst** [comment] 2022-02-12 09:26
Merged. I think this issue may be resolved.

**Closed** 2022-02-12 09:33 UTC
Labels: help wanted
